
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 15 13:13:25 NZST 2008
//----------------------------------------------------

/*
 * STANDARD ML OF NEW JERSEY COPYRIGHT NOTICE, LICENSE AND DISCLAIMER.
 * 
 * Copyright (c) 1989-1998 by Lucent Technologies
 * 
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose and without fee is hereby granted, provided
 * that the above copyright notice appear in all copies and that both the
 * copyright notice and this permission notice and warranty disclaimer appear
 * in supporting documentation, and that the name of Lucent Technologies, Bell
 * Labs or any Lucent entity not be used in advertising or publicity pertaining
 * to distribution of the software without specific, written prior permission.
 *
 * Lucent disclaims all warranties with regard to this software, including all
 * implied warranties of merchantability and fitness. In no event shall Lucent
 * be liable for any special, indirect or consequential damages or any damages
 * whatsoever resulting from loss of use, data or profits, whether in an action
 * of contract, negligence or other tortious action, arising out of or in
 * connection with the use or performance of this software. 
 *
 * Taken from this URL:
 * http://www.smlnj.org/license.html
 * 
 * This license is compatible with the GNU GPL (see section "Standard ML of New
 * Jersey Copyright License"):
 * http://www.gnu.org/licenses/license-list.html#StandardMLofNJ
 */

/*
 * Copyright 1996-1999 by Scott Hudson, Frank Flannery, C. Scott Ananian
 */

package weka.core.mathematicalexpression;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 7;
  public static final int AND = 29;
  public static final int IFELSE = 20;
  public static final int LT = 23;
  public static final int SIN = 13;
  public static final int PLUS = 6;
  public static final int OR = 30;
  public static final int RPAREN = 4;
  public static final int COS = 14;
  public static final int DIVISION = 8;
  public static final int NOT = 28;
  public static final int POW = 18;
  public static final int SQRT = 10;
  public static final int VARIABLE = 33;
  public static final int TRUE = 21;
  public static final int FLOOR = 17;
  public static final int RINT = 16;
  public static final int GT = 25;
  public static final int CEIL = 19;
  public static final int LPAREN = 3;
  public static final int LE = 24;
  public static final int LOG = 11;
  public static final int EXP = 12;
  public static final int BOOLEAN = 32;
  public static final int COMMA = 2;
  public static final int NUMBER = 31;
  public static final int EOF = 0;
  public static final int ABS = 9;
  public static final int GE = 26;
  public static final int FALSE = 22;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int EQ = 27;
  public static final int TAN = 15;
}

