//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.20 at 12:48:21 PM GMT 
//


package weka.core.pmml.jaxbbindings;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for ACTIVATION-FUNCTION.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ACTIVATION-FUNCTION">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="threshold"/>
 *     &lt;enumeration value="logistic"/>
 *     &lt;enumeration value="tanh"/>
 *     &lt;enumeration value="identity"/>
 *     &lt;enumeration value="exponential"/>
 *     &lt;enumeration value="reciprocal"/>
 *     &lt;enumeration value="square"/>
 *     &lt;enumeration value="Gauss"/>
 *     &lt;enumeration value="sine"/>
 *     &lt;enumeration value="cosine"/>
 *     &lt;enumeration value="Elliott"/>
 *     &lt;enumeration value="arctan"/>
 *     &lt;enumeration value="radialBasis"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ACTIVATIONFUNCTION {

    @XmlEnumValue("arctan")
    ARCTAN("arctan"),
    @XmlEnumValue("cosine")
    COSINE("cosine"),
    @XmlEnumValue("Elliott")
    ELLIOTT("Elliott"),
    @XmlEnumValue("exponential")
    EXPONENTIAL("exponential"),
    @XmlEnumValue("Gauss")
    GAUSS("Gauss"),
    @XmlEnumValue("identity")
    IDENTITY("identity"),
    @XmlEnumValue("logistic")
    LOGISTIC("logistic"),
    @XmlEnumValue("radialBasis")
    RADIAL_BASIS("radialBasis"),
    @XmlEnumValue("reciprocal")
    RECIPROCAL("reciprocal"),
    @XmlEnumValue("sine")
    SINE("sine"),
    @XmlEnumValue("square")
    SQUARE("square"),
    @XmlEnumValue("tanh")
    TANH("tanh"),
    @XmlEnumValue("threshold")
    THRESHOLD("threshold");
    private final String value;

    ACTIVATIONFUNCTION(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ACTIVATIONFUNCTION fromValue(String v) {
        for (ACTIVATIONFUNCTION c: ACTIVATIONFUNCTION.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
