/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 *    SetTaskStatusServlet.java
 *    Copyright (C) 2011-2013 University of Waikato, Hamilton, New Zealand
 *
 */

package weka.server;

import java.io.BufferedOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Used by slaves to pass back task status info to their master
 * 
 * @author Mark Hall (mhall{[at]}pentaho{[dot]}com)
 * @version $Revision$
 */
public class SetTaskStatusServlet extends WekaServlet {

  /** The context path for this servlet */
  public static final String CONTEXT_PATH = "/weka/setTaskStatus";

  /**
   * For serialization
   */
  private static final long serialVersionUID = 8377813643103264344L;

  /**
   * Constructs a new SetTaskStatusServlet
   * 
   * @param taskMap the task map maintained by the server
   * @param server a reference to the server itself
   */
  public SetTaskStatusServlet(WekaTaskMap taskMap, WekaServer server) {
    super(taskMap, server);
  }

  /**
   * Process a HTTP GET
   * 
   * @param request the request
   * @param response the response
   * 
   * @throws ServletException
   * @throws IOException
   */
  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {

    if (!request.getRequestURI().startsWith(CONTEXT_PATH)) {
      return;
    }

    // this should never be anything but a "client" servlet

    // IMPORTANT this will be the ID as generated by the slave, so it
    // will/should match a getRemoteID() in one of our WekaTaskEntries
    String taskName = request.getParameter("name");

    String taskStatus = request.getParameter("status");

    response.setStatus(HttpServletResponse.SC_OK);
    response.setContentType("application/octet-stream");

    ObjectOutputStream oos = null;
    WekaTaskMap.WekaTaskEntry found = null;
    NamedTask theTask = null;
    try {
      List<WekaTaskMap.WekaTaskEntry> entries = m_taskMap.getTaskList();
      for (WekaTaskMap.WekaTaskEntry te : entries) {
        if (te.getRemoteID() != null && te.getRemoteID().equals(taskName)) {
          found = te;
          break;
        }
      }

      if (found != null) {
        // update the local task with the remote information
        theTask = m_taskMap.getTask(found);
        theTask.getTaskStatus()
          .setExecutionStatus(Integer.parseInt(taskStatus));

        // pass on to our master?
        if (found.getCameFromMaster()) {
          m_server.sendTaskStatusInfoToMaster(found, theTask.getTaskStatus()
            .getExecutionStatus());
        }

        String okResult = WekaServlet.RESPONSE_OK;
        OutputStream out = response.getOutputStream();
        oos = new ObjectOutputStream(new BufferedOutputStream(out));
        oos.writeObject(okResult);
        oos.flush();
      } else {
        System.err
          .println("[WekaServer] Received a task status update from a slave, "
            + "but was unable to find task with remote ID '" + taskName
            + "' in the list of tasks registered with this server.");
        String errorResult = WekaServlet.RESPONSE_ERROR
          + ": Master received task status "
          + "update but couldn't find task with remote ID '" + taskName
          + "' in its " + "list of registered tasks";
        OutputStream out = response.getOutputStream();
        oos = new ObjectOutputStream(new BufferedOutputStream(out));
        oos.writeObject(errorResult);
        oos.flush();
      }
    } catch (Exception ex) {
      if (oos != null) {
        oos.writeObject(WekaServlet.RESPONSE_ERROR + " " + ex.getMessage());
        oos.flush();
      }
      ex.printStackTrace();
    } finally {
      if (oos != null) {
        oos.close();
      }
      if (theTask != null && found != null) {
        // make sure we persist this information
        m_server.persistTask(found, theTask);
      }
    }
  }
}
